# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = "paris-accessible"
  config.vm.box      = "precise64"
  config.vm.box_url  = "http://dl.dropbox.com/u/1537815/precise64.box"

  config.vm.network "private_network", ip: "192.168.33.10"



  
  # PROVISIONNING
  # config.omnibus.chef_version = '10.26.0'
  config.omnibus.chef_version = :latest

  config.vm.provision "chef_solo" do |chef|

    chef.cookbooks_path = "./cookbooks" , "./berks-cookbooks"

    chef.add_recipe "apt"
    chef.add_recipe "java"
    chef.add_recipe "elasticsearch"
    chef.add_recipe "neo4j-server::tarball"

    chef.json = {
      :java => {
        :install_flavor => "openjdk",
        :jdk_version =>  "7"
      },

      :elasticsearch => {
       :cluster => { :name => "elasticsearch" },
       :version => "1.3.2"
      }
    }


  end

  # PROVIDER
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

end
